# Generated by Django 3.2.3 on 2021-07-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25, null=True)),
                ('company_bio', models.CharField(max_length=200, null=True)),
                ('company_email', models.CharField(max_length=200, null=True)),
                ('company_phone', models.CharField(max_length=200, null=True)),
                ('company_mobile', models.CharField(max_length=200, null=True)),
                ('company_adress', models.CharField(max_length=200, null=True)),
                ('company_website', models.CharField(max_length=200, null=True)),
                ('company_instagram', models.CharField(max_length=200, null=True)),
                ('company_facebook', models.CharField(max_length=200, null=True)),
                ('company_pic', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
