# Generated by Django 3.2.3 on 2021-07-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210716_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Companie'},
        ),
    ]
