# Generated by Django 3.2.3 on 2021-07-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_mobile',
        ),
        migrations.AddField(
            model_name='company',
            name='company_about',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
