# Generated by Django 3.2.3 on 2021-07-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
