# Generated by Django 3.2.3 on 2021-07-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_company_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
